César p1 et p2
CamilleSimon/BTS2-CIEL-IR-VoieS-rie-2024-2025 pull request #34
Opened 2024-09-05 06:42 UTC by Haldredh

2024-09-07 11:51 UTC, CamilleSimon requested changes

2024-09-07 11:51 UTC, CamilleSimon commented on TP Code César partie 1.c
> +    int CesarInt; // caractère codé en int
Attention, les noms de variables commencent par des minuscules !

2024-09-07 11:51 UTC, CamilleSimon commented on TP Code César partie 1.c
> +        CesarInt = readChar + 6;
La clé doit être une variable globale

2024-09-07 11:51 UTC, CamilleSimon commented on TP Code César partie 2.c
> +        int CesarInt = c + key; // Appliquer la clé de chiffrement
Même remarque que pour la partie 1

2024-09-07 11:53 UTC, CamilleSimon commented
Pour la partie 1 : 2,5/3. Si tu veux améliorer ta note, tu peux commit les changements demander.

2024-09-08 20:28 UTC, CamilleSimon requested changes

2024-09-08 20:28 UTC, CamilleSimon commented on TP Code César partie 1.c
> +    int key = 6;
C'est toujours pas une variable globale.
Une variable globale doit être placée au début du fichier, en dehors des fonctions.

2024-09-08 20:28 UTC, Haldredh commented on TP Code César partie 1.c
> +    int CesarInt; // caractère codé en int
Ok, toutes les variables commencent par des minuscules maintenant.

2024-09-08 20:28 UTC, Haldredh commented on TP Code César partie 1.c
> +        CesarInt = readChar + 6;
C'est fait.

2024-09-08 20:28 UTC, Haldredh commented on TP Code César partie 2.c
> +        int CesarInt = c + key; // Appliquer la clé de chiffrement
Corrigé aussi.

2024-09-08 20:36 UTC, Haldredh commented on TP Code César partie 1.c
> +    int key = 6;
Done.
(soucis interface chaise clavier corrigé.)

2024-09-09 05:48 UTC, CamilleSimon approved these changes

2024-09-09 05:49 UTC, CamilleSimon approved these changes

2024-09-09 05:52 UTC, CamilleSimon commented
Partie 1 : 3/3
Partie 2 - optionnel : 4/4
Super travail 🎉

2024-09-09 05:53 UTC, merged