P1 tp_CESAR
CamilleSimon/BTS2-CIEL-IR-VoieS-rie-2024-2025 pull request #35
Opened 2024-09-05 06:45 UTC by TheglitchWTF

2024-09-07 12:37 UTC, CamilleSimon approved these changes

2024-09-07 12:38 UTC, CamilleSimon commented
Partie 1 validée

2024-09-07 12:52 UTC, CamilleSimon requested changes

2024-09-07 12:52 UTC, CamilleSimon commented on TP Code César partie 2.c
Beaucoup de chose à modifier pour que ce code compile et s'exécute dans erreur !
Pour l'instant tu as 0,5/4, c'est facilement améliorable en 4/4 !
Si tu as des questions concernants certaines lignes, mets des commentaires en me tagguant (@CamilleSimon ).

2024-09-09 14:09 UTC, TheglitchWTF commented
TP_Machine a café ready

2024-09-10 07:36 UTC, TheglitchWTF commented
Update TP Machine a café.c ready

2024-09-11 10:04 UTC, CamilleSimon commented on TP Code César partie 2.c
> +String recupsansv(String text) {
L'exécution du code ne sort jamais de cette fonction.

2024-09-16 12:09 UTC, closed without merging