TP guidé Exercice
CamilleSimon/BTS2-CIEL-IR-VoieS-rie-2024-2025 pull request #42
Opened 2024-09-06 08:36 UTC by PotatoesNation

2024-09-07 14:52 UTC, CamilleSimon requested changes

2024-09-07 14:52 UTC, CamilleSimon commented on TP guidé.md
Merci d'utiliser *un seul* `for`

2024-09-07 15:39 UTC, PotatoesNation commented on TP guidé.md
Bonsoir Madame, 
Je viens de modifier mon code à ce sujet en n'employant qu'une seule boucle for.

Cordialement

2024-09-07 16:13 UTC, CamilleSimon commented on TP guidé.md
Tu as testé ton code ? 😉

2024-09-07 16:16 UTC, CamilleSimon requested changes

2024-09-07 16:16 UTC, CamilleSimon commented on TP guidé.md
Et il faut une alternance majuscule/minuscule comme montré dans le sujet.

2024-09-07 16:18 UTC, PotatoesNation commented on TP guidé.md
Ah oui en effet.
Je vais revoir le code.
Merci

2024-09-07 17:30 UTC, PotatoesNation commented on TP guidé.md
Normalement cette fois ci, mon code marche et il affiche bien une majuscule une lettre sur deux.

Désolé pour le retard.

2024-09-07 17:53 UTC, CamilleSimon requested changes

2024-09-07 17:53 UTC, CamilleSimon commented on TP guidé.md
> +}
Cette femeture d'accolade est en trop

2024-09-07 19:33 UTC, CamilleSimon approved these changes

2024-09-07 20:22 UTC, merged

2024-09-09 06:15 UTC, CamilleSimon commented
Partie 1 : 3/3

2024-09-17 09:00 UTC, CamilleSimon commented
@PotatoesNation où est ta pull request pour la partie 2 ?
La dead line était lundi 16 septembre 8h comme annoncé en cours le vendredi 13 septembre.