Create TP code cesar pt2
CamilleSimon/BTS2-CIEL-IR-VoieS-rie-2024-2025 pull request #74
Opened 2024-09-10 16:04 UTC by JaurisY

2024-09-16 16:46 UTC, CamilleSimon commented
Je ne vois pas ta partie 1. Est ce que tu l'as bien mise dans sun fichier séparé ?

2024-09-18 11:52 UTC, CamilleSimon requested changes

2024-09-18 11:52 UTC, CamilleSimon commented on TP code cesar pt2
> +				for(j = key; j > 0; j--)
Pourquoi ? `j` sert à quoi ?

2024-09-18 11:52 UTC, CamilleSimon commented on TP code cesar pt2
> +				for(j = key; j > 0; j--)
Même question

2024-09-18 11:53 UTC, CamilleSimon commented
Partie 1 : 3/3 🎉 
Partie 2 : 3/4

2024-09-18 13:00 UTC, JaurisY commented on TP code cesar pt2
> +				for(j = key; j > 0; j--)
j est là pour ajouter la clé 1 par 1 ce qui permet de vérifier la conditions en dessous a chaque fois ce qui permet alors de sortir de la table ASCII si par exemple on met la clé 6 avec z ou la clé 10 avec y ou la clé  15 avec w ... On peut alors même mettre des clés supérieure a 26 sans aucun problème ce qui quoiqu'il arrive évite les caractères spéciaux.

2024-09-24 15:20 UTC, merged