Create tp_partie_2
CamilleSimon/BTS2-CIEL-IR-VoieS-rie-2024-2025 pull request #85
Opened 2024-09-11 15:58 UTC by lucasd363

2024-09-16 17:14 UTC, CamilleSimon commented
Partie 1 - Note provisoire : 2/3

2024-09-16 17:38 UTC, CamilleSimon requested changes

2024-09-16 17:38 UTC, CamilleSimon commented on tp_partie_2
Pour le test `abcdefghijklmnopqrstuvwxyz`, ton programme donne `ghijklmnopqrstuvwxyz{bcde`.
A modifier !

2024-09-18 12:49 UTC, CamilleSimon commented
Partie 1 : 3/3 🎉

2024-09-18 12:50 UTC, CamilleSimon approved these changes

2024-09-18 12:50 UTC, merged

2024-09-18 15:53 UTC, lucasd363 reviewed
TP partie 2
char operation;
char key = 6;
int readChar;
int buff;
void setup()
{
    Serial.begin(9600);
   	
}

void loop()
{
  
	int Tableau[150];
    int buff = Serial.available();
    char readChar;
    int i=0;
  	String s = "";
  int separ=s.indexOF(',',3)
    
  	buff= s + readChar; 
  	if (s.substring(0)
        {
          ;
        }
  
  	while(buff > 0) // tant qu'il reste des caractères dans le buffer
    {
      readChar = Serial.read();
      Tableau[i]=readChar;
      i++;
    }
     if (operation == 0 ) 
     {
       dechiffrement(message);
     }
    else 
    {
      chiffrement(message);
    }
}

String chiffrement(String message)
{
  String messagechiffre;
  for(int i=0;i<message.length();i++)
  {
    readChar = message[i]+key ; // lecture du caractère
       if(readChar > 123 )
      {
          readChar -= 26;      
      }
        
        Serial.print(message); // envoi du caractère
       int buff = Serial.available(); // mise à jour du nombre de caratères restant
        char message = 0 ; // caractère à lire
  }
 
}
String dechiffrement(String message)
{
  String messagedechiffre;
  for(int i=0;i<message.length();i++)
  {
   readChar = message[i]+key ; // lecture du caractère
       if(readChar > 96 )
      {
          readChar += 26;      
      }
        
        Serial.print(message); // envoi du caractère
        buff = Serial.available(); // mise à jour du nombre de caratères restant
        char readChar = 0 ; // caractère à lire
  }
 
}

2024-09-18 15:55 UTC, lucasd363 reviewed
char operation;
char key = 6;
int readChar;
int buff;
void setup()
{
    Serial.begin(9600);
   	
}

void loop()
{
  
	int Tableau[150];
    int buff = Serial.available();
    char readChar;
    int i=0;
  	String s = "";
  int separ=s.indexOF(',',3)
    
  	buff= s + readChar; 
  	if (s.substring(0)
        {
          ;
        }
  
  	while(buff > 0) // tant qu'il reste des caractères dans le buffer
    {
      readChar = Serial.read();
      Tableau[i]=readChar;
      i++;
    }
     if (operation == 0 ) 
     {
       dechiffrement(message);
     }
    else 
    {
      chiffrement(message);
    }
}

String chiffrement(String message)
{
  String messagechiffre;
  for(int i=0;i<message.length();i++)
  {
    readChar = message[i]+key ; // lecture du caractère
       if(readChar > 123 )
      {
          readChar -= 26;      
      }
        
        Serial.print(message); // envoi du caractère
       int buff = Serial.available(); // mise à jour du nombre de caratères restant
        char message = 0 ; // caractère à lire
  }
 
}
String dechiffrement(String message)
{
  String messagedechiffre;
  for(int i=0;i<message.length();i++)
  {
   readChar = message[i]+key ; // lecture du caractère
       if(readChar > 96 )
      {
          readChar += 26;      
      }
        
        Serial.print(message); // envoi du caractère
        buff = Serial.available(); // mise à jour du nombre de caratères restant
        char readChar = 0 ; // caractère à lire
  }
 
}